SALDO = 4500
SAQUE = 2000

# IGUALDADE: ==
print(SALDO == SAQUE)

# DIFERENÇA: !=
print(SALDO != SAQUE)

# MAIOR IGUAL OU MAIOR QUE
print(SALDO >= SAQUE)
print(SALDO > SAQUE)

# MENOR IGUAL OU MENOR QUE
print(SALDO <= SAQUE)
print(SALDO < SAQUE)